### ISSUE TITLE
Consider accepting a function for backoff option

### ISSUE THREAD

**Issue by andrejbaran** [machuga/keep-trying#1]
Hey!

It would be great if the backoff option would accept a function with signature `(attempt: number) -> number`. This would be useful when one would like to use exponential backoff.

**Comment by machuga** [comment]
Hey buddy!

Sounds like a great idea to me 👍 

Did you want to implement it or would you like me to?

**Comment by markprovan** [comment]
@machuga I can have a go at this if you like?

**Comment by machuga** [comment]
@markprovan sure, feel free!

**Comment by machuga** [comment]
Updated version allows exponential backoff (full and equal), and accepts custom function. Also adds jitter options.
